server:
  port: 9494

spring:
  datasource:
    password: password
    url: jdbc:postgresql://microbank_client_db:5432/client_db
    username: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
