server:
  port: 9595

spring:
  datasource:
    password: password
    url: jdbc:postgresql:/microbank_bank_db:5434/bank_db
    username: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true