spring:
  application:
    name: banking-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microbank
          jwk-set-uri: http://localhost:8080/realms/microbank/protocol/openid-connect/certs

  cloud:
    config:
      override-system-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5434/bank_db  # ✅ FIXED: use double slashes
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  auth:
    converter:
      resource-id: maiita
      principle-attribute: preferred_username

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9595
