spring:
  config:
    import: optional:configserver:http://config-server:9090
  application:
    name: banking-service

  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak_auth:8080/realms/microbank
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
    auth:
      converter:
        resource-id: maiita
        principle-attribute: preferred_username
