spring:
  application:
    name: client-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/microbank
          jwk-set-uri: http://localhost:8080/realms/microbank/protocol/openid-connect/certs

  cloud:
    config:
      override-system-properties: false

  datasource:
    url: jdbc:postgresql://localhost:5432/client_db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  auth:
    converter:
      resource-id: microbank
      principle-attribute: preferred_username

keycloak:
  server-url: http://localhost:8080
  realm: microbank

  client-id: microbank
  client-secret: foFirb0J7o9KM87Y9y75vw0knTukhRft

  admin-cli: admin-cli
  admin-secret: SlvI2537ftAaXilDLuiKCz9LWKMsEAOV

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9494

management:
  tracing:
    sampling:
      probability: 1.0
