spring:
  config:
    import: optional:configserver:http://config-server:9090
  application:
    name: client-service

  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri:  http://keycloak_auth:8080/realms/microbank
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: microbank
      principle-attribute: preferred_username

keycloak:
  server-url: http://keycloak_auth:8080
  realm: microbank
  client-id: microbank
  client-secret: SYZd71iMp4TvnUqgPewmbriC48ueqCzy

